/* Generated by bin2c, do not edit manually */
#ifndef __sysinfo_h_included
#define __sysinfo_h_included

/* Contents of file sysinfo */
extern const long int sysinfo_size;
extern const unsigned char sysinfo[7444];

#endif    /* __sysinfo_h_included */
